 
 ---- Principal
 ALTER ENDPOINT Endpoint_A STATE=STOPPED 
 ALTER ENDPOINT Endpoint_A STATE=STARTED
 
 --- Espelho
ALTER ENDPOINT Endpoint_B STATE=STOPPED 
ALTER ENDPOINT Endpoint_B STATE=STARTED
 
 